# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    binary: jt
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  -
    # Name template of the recipe
    # Default to project name
    name: jt

    # GitHub/GitLab repository to push the formula to
    # Gitea is not supported yet, but the support coming
    tap:
      owner: StevenACoffman
      name: homebrew-jt
      # Optionally a token can be provided, if it differs from the token provided to GoReleaser
      # token: "{{ .Env.GITHUB_AUTH_TOKEN }}"
    folder: Formula
    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/StevenACoffman/jt"

    # Template of your app's description.
    # Default is empty.
    description: jt is a CLI tool for viewing and manipulating JIRA issues.

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "MIT"

    # Custom install script for brew.
    # Default is 'bin.install "program"'.
    install: |
      bin.install "jt"
